clusters = na, eu
na.bootstrap.servers = kafka:29092
eu.bootstrap.servers = kafka:29092
na->eu.enabled = true
eu->na.enabled = true
na->eu.topics = na.cdc.app_na.companies
eu->na.topics = eu.cdc.app_eu.companies
replication.policy.class = org.apache.kafka.connect.mirror.IdentityReplicationPolicy
sync.topic.configs.enabled = false
